# .github/workflows/main.yml
name: Build and Commit Resume PDF with Bun (Docker)

on:
  push:
    branches:
      - main

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/puppeteer/puppeteer:latest
      options: --user root
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install project dependencies with Bun
        run: bun install

      - name: Build React app with Bun
        run: bun run build
        env:
          CI: true

      - name: Generate PDF with Bun
        run: bun run generate-pdf.ts

      - name: Commit and push PDF
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add .
          if git diff --staged --quiet; then
            echo "No changes to PDF, skipping commit."
          else
            git commit -m "Automated: Update resume PDF"
            git push
          fi
